### ISSUE TITLE
Schedule Page : Content not displayed 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#10]
Screenshot: Inner Page - 03
![inner page - 03](https://cloud.githubusercontent.com/assets/12791909/8075651/68d74082-0f75-11e5-82d7-d4c28de59efa.jpg)

**Comment by ramoncebudigital** [comment]
iframe not loaded, maybe it's because of the internet connection.
working on my end.
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/8098813/6bfa380c-1027-11e5-93e4-d97c489a6d48.png)

**Comment by ermatitan** [comment]
problem re-occurs on Samsung S-4

![image](https://cloud.githubusercontent.com/assets/12791909/8720316/97040310-2be4-11e5-8712-9a2559cc4ff9.png)

**Comment by rexcebudigital** [comment]
Hi Erma, I havent updated anything yet for this issue because I dont see the issue on my end. I have checked using andriod device, Ipad Air ang chrome device mode and emulator website.
Kindly try to clear your cache and wait for the page to load. If the issue still occur please provide steps to replicate. Thanks.
